name: PHPUnit

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    if: (!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]'))
    env:
      PHP_INI_VALUES: assert.exception=1, zend.assertions=

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        DB: [ 'mysqli' ]
        compiler: [ default ]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: travis
          MYSQL_PASSWORD: travis
          MYSQL_DATABASE: ci_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install PHP${{ matrix.php }} - DB ${{ matrix.DB }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, pecl
        extensions: imagick, mysqli, pdo, pdo_mysql, mbstring
        ini-values: ${{ env.PHP_INI_VALUES }}
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-   

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: PHPUnit Test
      run: |
        php -d error_reporting=E_ALL -d zend.enable_gc=0 -d date.timezone=UTC -d mbstring.func_overload=7 -d mbstring.internal_encoding=UTF-8 vendor/bin/phpunit --coverage-text --configuration tests/travis/${{ matrix.DB }}.phpunit.xml
      env:
        XDEBUG_MODE: coverage

